const contact = '<a href="mailto:stanforddevcontact@gmail.com">stanforddevcontact@gmail.com</a>';
const cancelLinks =
  '<a href="https://apps.apple.com/account/subscriptions">Apple subscriptions</a> or <a href="https://play.google.com/store/account/subscriptions">Google Play subscriptions</a>';

export const pages = {
  terms: {
    title: 'Terms of use',
    description: 'Parish Pass terms, business subscriptions, cancellation and customer support.',
    body: `<p>These terms govern Parish Pass, including versions named SDS Local, provided by StanfordDev. By using the service, you agree to these terms. Questions: ${contact}.</p>
<h2>Accounts and permitted use</h2><p>Use accurate account information and protect your sign-in credentials. Business owners must be authorized to represent their businesses and to enter subscription and service arrangements. You are responsible for actions performed through your account. Do not impersonate others, publish unlawful or misleading content, harass users, manipulate reviews or rewards, infringe intellectual property, or attempt unauthorized access.</p>
<h2>Customer and business features</h2><p>Customer discovery and ordinary customer account features are free. Business plans provide the capabilities listed on the subscription screen for the selected plan. Availability can depend on location, device, business approval, and completion of payment-provider setup. A subscription does not guarantee visibility, customers, sales, or business approval.</p>
<h2>Business subscriptions</h2><p class="notice">A business subscription is a recurring purchase linked to your Parish Pass account. Before confirming, review the full price, billing period, available benefits, and renewal terms displayed in the app and by your store.</p><p>Subscriptions purchased on iOS are billed by Apple; subscriptions purchased on Android are billed by Google Play. Your store charges the amount shown at confirmation, including any applicable taxes. Subscriptions renew automatically unless cancelled through the purchasing store before its renewal deadline. No free trial applies unless the store confirmation explicitly offers one. Any price change follows the store's notice and consent requirements.</p><p>Manage, change, or cancel through ${cancelLinks}, using the store account that made the purchase. Cancellation ordinarily stops future renewal while access continues through the paid period, unless the store refunds or revokes the purchase. Store rules determine upgrade and downgrade timing. Changing platforms does not cancel a subscription in the original store. Use Restore purchases in the app while signed in to the original Parish Pass account; contact support if you cannot recover that account.</p>
<h2>Setup, review, and rejected businesses</h2><p>Billing starts when the store confirms your subscription. Time spent preparing a business page or awaiting review is part of the paid subscription period. Approval is separate from payment. If a business cannot be approved, contact ${contact} for the reason and available next steps, cancel future renewal if desired, and request any refund through the purchasing store. Payment does not bypass moderation and refunds are not automatic on rejection.</p>
<h2>Business content and customer transactions</h2><p>You retain ownership of content you submit and grant us permission to host, display, and process it to provide the service. Publish only content you have the right to use. Business profiles, schedules, offers, rewards, and responses are supplied by businesses and may change. Businesses are responsible for their goods, services, fulfillment, appointment policies, taxes, and customer remedies. Contact the business first about an order or booking and contact us for app or account issues. Purchases of physical goods or services from businesses are separate from the business owner's app subscription and can use supported payment processors.</p>
<h2>Moderation and service availability</h2><p>We may remove content or restrict accounts that violate these terms, threaten safety, or interfere with the service. Access to paid tools can end when a subscription expires or is revoked. We work to maintain the service, but cannot guarantee uninterrupted access or the accuracy of information provided by businesses. To the extent permitted by law, the service is provided as available. These terms do not exclude rights or remedies that applicable law does not allow us to exclude.</p>
<h2>Privacy, deletion, and changes</h2><p>Our <a href="/privacy.html">privacy policy</a> explains data handling. See <a href="/delete-account.html">account deletion</a> for instructions and effects. Deleting your account does not cancel store billing; cancel separately if you do not want renewal. Material changes to these terms will be communicated through the service or another appropriate notice before they take effect.</p>
<h2>Apple app license</h2><p>For the iOS application, Apple's <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Standard Licensed Application End User License Agreement</a> applies to the app license. These service terms supplement it and do not replace mandatory store terms or your statutory rights.</p>`,
  },
  privacy: {
    title: 'Privacy policy',
    description:
      'How Parish Pass handles account information, location, business content and purchase data.',
    body: `<p>This policy explains how StanfordDev handles information in Parish Pass, including versions named SDS Local. For privacy questions or requests, contact ${contact}.</p>
<h2>Information used to provide the app</h2><ul><li><strong>Account information:</strong> email, account identifier, profile name, authentication and account preferences. Apple or Google sign-in can supply account information you authorize.</li><li><strong>Activity and content:</strong> followed or saved businesses, reviews and replies, event responses, reminders, rewards memberships and transactions, service requests, bookings, pickup orders, and information you submit with those actions.</li><li><strong>Business information:</strong> profile and contact details, addresses and mobile stops, photos, menus or services, schedules, offers, staff access, and business activity needed to operate your page.</li><li><strong>Subscriptions and payments:</strong> store product and transaction identifiers, purchase dates, renewal and cancellation status, and account-linked access. Apple and Google process subscription payment details. Supported business payment processors handle payment credentials and connected-business information for commerce features.</li><li><strong>Technical information:</strong> device and app information, network request and error records, session information, and notification registrations used for delivery, security, troubleshooting, and software updates.</li></ul>
<h2>Location, photos, and notifications</h2><p>With your permission, location supports nearby business discovery. Optional nearby mobile-business alerts can use background location even when the app is closed or not in use. Geofence checks for these alerts are evaluated on your device; this location is not used for advertising. Turn nearby alerts off in the app or change location permission in device settings. Locations a business owner deliberately publishes are visible to customers.</p><p>Camera or photo access supports images and scanning that you choose to use. Notification permission supports alerts and reminders. You can control permissions in device settings; declining a permission may prevent its associated feature without requiring a paid subscription.</p>
<h2>Uses and sharing</h2><p>We use information to authenticate accounts, deliver requested features, maintain business pages and subscriptions, provide support, prevent abuse, and secure and improve the service. Public business pages, reviews, replies, and published events can be visible to other users. Businesses receive the information needed to respond to your requests, bookings, orders, event participation, or rewards activity; their own data practices apply to information they independently hold.</p><p>Service providers process information needed for their roles: Supabase for authentication, database and storage; Expo for app hosting, updates and notification services; RevenueCat and Apple or Google for subscription validation; and supported Stripe or Square integrations for payments when those features are used. We may disclose information when required by law, to address abuse or security threats, or as part of a service ownership change with appropriate notice. We do not sell personal information or use background alert location for advertising.</p>
<h2>Security and retention</h2><p>Hosted service connections use HTTPS, account authentication and access controls. No system can guarantee absolute security. Active account data is kept while needed for the service or until deletion. Account deletion removes the profile and associated private account records, memberships, reminders, notification registrations, and business access. Businesses with no other active owner and their content are deleted. Shared businesses and legitimate business records can remain with another owner after your access and attribution are removed or reassigned.</p><p>Limited records may remain where needed for transaction disputes, fraud prevention, legal obligations, deletion processing, or service-provider backups until those purposes or backup lifecycles end. Apple, Google, businesses and payment processors may retain transaction records under their own policies. Deletion of your app account does not delete those separately held records or cancel a store subscription. Contact us for questions about a particular record.</p>
<h2>Your choices and requests</h2><p>Edit your profile and preferences in Account, control notifications and nearby alerts, and manage business blocking under Privacy &amp; Safety. Request access, correction, or deletion of personal information at ${contact}. We may verify your account before acting and respond in accordance with applicable law. See <a href="/delete-account.html">Delete account</a> for both in-app deletion and an external request route that does not require the app.</p>
<h2>Children and policy updates</h2><p>The service is not directed to children under 13. If you believe a child has provided personal information without appropriate authorization, contact us so we can investigate and remove it where required. We will publish updates here and provide appropriate notice of material changes.</p>`,
  },
  support: {
    title: 'Support',
    description:
      'Help with Parish Pass accounts, business subscriptions, purchases and app issues.',
    body: `<p>For Parish Pass support, including versions named SDS Local, email ${contact}.</p><p>Include your app version, phone platform, a description of the issue, and the email associated with your account. For purchase issues, include the product name and a store order reference if available. Do not send passwords, verification codes, full card details, or service credentials.</p>
<h2>Subscriptions, cancellation, and refunds</h2><p>Open Business plans in the app to restore purchases or manage your subscription. Use the same Parish Pass account and purchasing store account. Manage renewal and cancellation through ${cancelLinks}. Deleting the app or your Parish Pass account does not cancel a subscription.</p><p>Apple and Google handle refunds for purchases billed through their stores. Use <a href="https://reportaproblem.apple.com/">Apple's refund request page</a> or <a href="https://support.google.com/googleplay/answer/2479637">Google Play's refund instructions</a>. If your purchase succeeded but access is missing, contact us before trying to buy again. We can investigate access; the store determines refund eligibility.</p>
<h2>Business approval and customer issues</h2><p>Contact us about a business approval decision or a problem creating your page. Your subscription begins at purchase and includes setup and review time. For a business's goods, services, rewards, bookings, or fulfillment, contact that business using its profile. For an app error or safety concern, contact us with the relevant business name and details.</p>
<h2>Account and privacy requests</h2><p>See <a href="/delete-account.html">account deletion instructions and requests</a> or our <a href="/privacy.html">privacy policy</a>. You may email a deletion or privacy request without having the app installed.</p>`,
  },
  'delete-account': {
    title: 'Delete account',
    description: 'Delete your Parish Pass account in the app or request deletion by email.',
    body: `<p>You can delete your Parish Pass account, including accounts created in SDS Local, using either route below. There is no deletion fee.</p>
<h2>Delete in the app</h2><ol><li>Sign in and open <strong>Account → Account &amp; data → Delete account</strong>.</li><li>Review the affected businesses and account data.</li><li>Type <strong>DELETE</strong> and choose <strong>Permanently delete account</strong> to confirm.</li></ol>
<h2>Request deletion without the app</h2><p>Email ${contact} with the subject <strong>Parish Pass account deletion</strong>, preferably from the email associated with your account. State that you want your account and associated personal data deleted. Include your account email if you are contacting us from a different address. We will verify ownership and any affected shared businesses before carrying out the request. Do not send a password or verification code.</p><p><a class="request" href="mailto:stanforddevcontact@gmail.com?subject=Parish%20Pass%20account%20deletion&amp;body=Please%20delete%20my%20Parish%20Pass%20account%20and%20associated%20personal%20data.%0AAccount%20email%3A%20">Start an account deletion request</a></p>
<h2>What deletion does</h2><p>Deletion removes your profile, saved businesses, rewards memberships, reminders, notification registrations, and business access. Businesses you own alone and their content are deleted. Shared businesses remain with another active owner; your access is removed. Deletion is permanent. Pending business orders or payment connections may need to be resolved before business deletion can finish; contact support if the app reports that condition.</p><p>Some records held for disputes, fraud prevention, legal obligations, deletion processing or backups, and records independently held by businesses, stores or payment processors may remain as described in the <a href="/privacy.html">privacy policy</a>. To ask about specific data without closing your account, email the same support address with a description of your request.</p>
<p class="notice"><strong>Cancel store billing separately.</strong> Account deletion does not cancel Apple or Google subscriptions. Use ${cancelLinks} first if you do not want your subscription to renew.</p>`,
  },
};
