const fs=require('fs'),crypto=require('crypto');
const templates=require('./templates.cjs');
const {query}=require('./staging.cjs');
const dir=require('path').resolve('.codex-tmp/playground');fs.mkdirSync(dir,{recursive:true});const seed='parish-playground-20260929';
const id=s=>{const h=crypto.createHash('sha256').update(seed+':'+s).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-8${h.slice(17,20)}-${h.slice(20,32)}`};
const q=v=>v==null?'null':typeof v==='number'||typeof v==='boolean'?String(v):"'"+(typeof v==='object'?JSON.stringify(v):String(v)).replaceAll("'","''")+"'"+(typeof v==='object'?'::jsonb':'');
const date=(days,hour=16)=>{const d=new Date('2026-09-29T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);d.setUTCHours(hour,0,0,0);return d.toISOString()};
const rows={},add=(t,r)=>(rows[t]??=[]).push(r);
const names=['Avery','Camille','Jordan','Miles','Nora','Theo','Elise','Isaiah','Hazel','Leo','Maya','Owen','Ruby','Elliot','Sofia','Caleb','Audrey','Julian','Stella','Emmett'];
const surnames=['Broussard','Landry','Ellis','Brooks'];
const usersPath=dir+'/accounts.private.json';
const users=fs.existsSync(usersPath)?JSON.parse(fs.readFileSync(usersPath)):Array.from({length:80},(_,i)=>({id:id('user:'+i),name:names[i%20]+' '+surnames[Math.floor(i/20)],email:`playground${String(i+1).padStart(2,'0')}@demo.sdslocal.test`,password:'Parish!'+crypto.randomBytes(15).toString('base64url'),role:i<54?'owner':i<70?'customer/staff':'customer'}));
fs.writeFileSync(usersPath,JSON.stringify(users,null,2));
const towns=[['Hammond','70401',30.5044,-90.4612],['Hammond','70403',30.4924,-90.4823],['Ponchatoula','70454',30.4388,-90.4415],['Hammond','70401',30.5195,-90.4738],['Covington','70433',30.4755,-90.1009],['Madisonville','70447',30.4075,-90.1562],['Mandeville','70448',30.3582,-90.0656],['Hammond','70403',30.4840,-90.4560]];
const prefixes=['Copper Oak','Little Bayou','Willow & Pine','Golden Hour','Juniper Lane','Riverbend','Cypress Corner','Blue Heron'];
const colors=['#345C50','#785140','#3D6174','#7A4D61','#566C42','#3D6260','#785F35','#4F5872'];
const businesses=[],forms=[];
for(const [ti,t] of templates.entries()) for(let j=0;j<8;j++){
 const n=ti*8+j,owner=users[n%54],staff=users[54+n%16],bid=id('business:'+n),town=towns[j],name=prefixes[(j+ti)%8]+' '+t.suffix;
 const b={id:bid,created_by:owner.id,slug:'demo-playground-'+t.key+'-'+(j+1),name,business_type:t.type,status:'active',description:t.description+' '+['Stop in for friendly service and a relaxed neighborhood experience.','Our team takes pride in small details and a warm welcome.','Built around reliable service and a connection to our community.'][j%3]+' Fictional staging business; all contact details and activity are for testing.',category_summary:t.label,phone:`(985) 555-01${String(n%100).padStart(2,'0')}`,email:`hello@${t.key}-${j+1}.example`,website_url:'https://example.com',address_line_1:`${120+ti*14+j*3} ${['Oak Avenue','Market Street','Pine Street','Willow Lane'][ti%4]} (test address)`,city:town[0],region_code:'LA',postal_code:town[1],timezone:'America/Chicago',primary_color:colors[j],accent_color:'#E7B873',service_area_type:t.type==='services'&&t.key!=='salon'&&t.key!=='pet'?'radius':'at_location',service_radius_miles:t.type==='services'&&t.key!=='salon'&&t.key!=='pet'?25:null,service_area:t.type==='services'?'Hammond, Ponchatoula and nearby Northshore communities':null,approved_at:date(-90),created_at:date(-100-n),latitude:town[2]+(ti-10)*.00065,longitude:town[3]+(ti-10)*.0006,template:t.key,category:t.category};
 businesses.push(b);const {latitude,longitude,template,category,...br}=b;add('businesses',br);
 add('business_members',{id:id('owner:'+bid),business_id:bid,user_id:owner.id,role:'owner',is_active:true});
 add('business_members',{id:id('staff:'+bid),business_id:bid,user_id:staff.id,role:'staff',is_active:true});
 for(let d=0;d<7;d++)add('business_hours',{business_id:bid,day_of_week:d,interval_number:1,opens_at:['coffee','bakery','brunch','mobilecoffee'].includes(t.key)?'06:30':'09:00',closes_at:['pizza','cajun','music','tacos','bbq'].includes(t.key)?'21:00':'18:00',is_closed:t.type==='services'&&d===0});
 const sections=[id('section:'+bid+':0'),id('section:'+bid+':1')];
 for(let k=0;k<2;k++)add('offering_sections',{id:sections[k],business_id:bid,name:k?(t.type==='services'?'Specialty services':t.type==='retail'?'Accessories & extras':'Sides & favorites'):(t.type==='services'?'Services & consultations':t.type==='retail'?'The collection':t.type==='entertainment_venue'?'Experiences':'House specialties'),description:k?'Something extra to complete your visit.':'Explore our most-loved choices.',display_order:k,is_visible:true});
 t.items.forEach(([iname,price,description],k)=>add('offering_items',{id:id('item:'+bid+':'+k),business_id:bid,section_id:sections[k<4?0:1],name:iname,description,price_minor:price+((j%3)*25*(price>0)),currency:'USD',is_available:true,is_featured:k===0,is_visible:true,display_order:k}));
 const food=['food_drink','mobile'].includes(t.type),program=id('program:'+bid),eligible=t.items.slice(0,3).map(([iname],k)=>({provider:'stripe',variationId:id('item:'+bid+':'+k),name:iname}));
 add('loyalty_programs',{id:program,business_id:bid,name:prefixes[(j+ti)%8]+' Rewards',reward_description:food?'Choose a complimentary menu favorite after 8 visits.':t.type==='services'?'A 15% thank-you discount after 300 points.':'Enjoy 15% off after earning 200 points.',stamps_required:8,program_type:food?'visits':'points',points_per_dollar:food?null:2,points_required:food?null:t.type==='services'?300:200,terms:'One reward per visit. Free menu rewards cover the base item; paid extras cost extra. Test program with no cash value.',is_active:true,checkout_reward_type:food?'free_item':'percent_discount',checkout_reward_percent:food?null:15,checkout_reward_enabled:false,checkout_reward_items:food?eligible:[]});
 const events=[];
 for(let k=0;k<6;k++){const day=[-28,-14,-4,3,10,24][k]+j%3,e={id:id('event:'+bid+':'+k),business_id:bid,slug:'playground-'+t.key+'-'+k,title:t.event+['',' — weekend session',' — community edition'][k%3],description:`Join ${name} for ${t.event.toLowerCase()}. ${t.type==='entertainment_venue'?'Doors open 30 minutes early. Meet our performers and instructors before the session.':'Meet the team, learn something new and enjoy a relaxed gathering with neighbors.'} Includes all listed materials. Please arrive 10 minutes early; contact us about accessibility. Fictional staging event, not a real-world booking.`,starts_at:date(day,k%2?23:16),ends_at:date(day,k%2?25:18),timezone:'America/Chicago',location_mode:'business',address_text:b.address_line_1+', '+b.city+', LA',age_note:t.key==='music'?'Ages 16+ with an adult':'All ages welcome',capacity_text:t.type==='entertainment_venue'?'60 guests':'24 guests',rsvp_limit:t.type==='entertainment_venue'?60:24,is_published:true,created_at:date(day-30)};add('events',e);events.push(e)}
 for(let k=0;k<3;k++)add('business_updates',{id:id('update:'+bid+':'+k),business_id:bid,created_by:owner.id,update_type:'announcement',title:[`This week at ${name}`,'Meet your neighborhood team','A new season, a few new favorites'][k],body:[`We are looking forward to seeing you this week. Explore our ${food?'menu':t.type==='services'?'services':'latest collection'} and upcoming events here on Parish Pass.`,`A warm welcome from our team. We are happy to answer questions and help you plan your next visit.`,`Our seasonal favorites are ready. Browse the details and save an upcoming event to join us.`][k],created_at:date(-k*5-1)});
 if(t.type==='mobile') for(let k=0;k<16;k++){const loc=[['Cate Square Park','279 N Oak St, Hammond, LA',30.5076,-90.4643],['Downtown Ponchatoula','125 W Pine St, Ponchatoula, LA',30.4395,-90.4415],['Hammond market area','2 W Thomas St, Hammond, LA',30.5046,-90.4614]][(k+j)%3];add('business_location_stops',{id:id('stop:'+bid+':'+k),business_id:bid,title:(k%2?'Dinner at ':'Lunch at ')+loc[0],address_text:loc[1],latitude:loc[2],longitude:loc[3],starts_at:date(k-2,k%2?22:15),ends_at:date(k-2,k%2?26:20),timezone:'America/Chicago',is_published:true})}
 if(t.type==='services'){
  add('appointment_settings',{business_id:bid,enabled:true,timezone:'America/Chicago',minimum_notice_minutes:120,booking_horizon_days:60,slot_interval_minutes:30,automatically_confirm:j%2===0,cancellation_cutoff_minutes:1440,cancellation_terms:'Please reschedule at least 24 hours before your visit. For urgent changes, contact the team.',public_instructions:t.key==='pet'?'Bring current vaccination information and tell us about sensitivities.':t.key==='salon'?'Bring inspiration photos and arrive with dry hair unless instructed otherwise.':'Describe your project and provide access instructions before your appointment.',updated_by:owner.id});
  const res=[id('resource:'+bid+':0'),id('resource:'+bid+':1')];res.forEach((rid,k)=>add('appointment_resources',{id:rid,business_id:bid,user_id:k?staff.id:owner.id,name:(k?staff:owner).name,is_active:true}));
  for(let d=1;d<=6;d++)add('appointment_weekly_windows',{id:id('window:'+bid+':'+d),business_id:bid,day_of_week:d,opens_at:'09:00',closes_at:d===6?'14:00':'17:00'});
  for(let k=0;k<5;k++){const it=rows.offering_items.find(i=>i.id===id('item:'+bid+':'+k)),sid=id('service:'+bid+':'+k),mins=[30,60,90,120,45][k];add('appointment_services',{id:sid,business_id:bid,offering_item_id:it.id,name:it.name,description:it.description,duration_minutes:mins,buffer_minutes:15,price_minor:it.price_minor,currency:'USD',payment_policy:'pay_in_person',price_is_fixed:k!==0,capacity:1,requires_resource:true,requires_approval:k===0,is_bookable:true,public_instructions:'Your team will confirm the details before the visit. Pay in person after service.'});for(const rid of res)add('appointment_service_resources',{business_id:bid,service_id:sid,resource_id:rid});}
  const specific={salon:[['goal','What would you like to change?','long_text'],['color_history','Have you colored your hair in the last six months?','yes_no'],['hair_length','Current hair length','choice',['Short','Shoulder length','Long']]],cleaning:[['size','Approximate square footage','number'],['bedrooms','Number of bedrooms','number'],['frequency','Cleaning frequency','choice',['One time','Weekly','Every two weeks','Monthly']],['pets','Are there pets in the home?','yes_no']],hvac:[['issue','What is your system doing?','long_text'],['equipment','Equipment type','choice',['Central air','Heat pump','Mini split','Not sure']],['age','Approximate system age in years','number']],landscape:[['project','What would you like done?','long_text'],['yard','Yard size','choice',['Small','Medium','Large']],['access','Gate and yard access instructions','long_text']],pet:[['pet_name','Pet name','text'],['breed','Breed or mix','text'],['weight','Weight in pounds','number'],['vaccines','Are vaccinations current?','yes_no']]}[t.key];
  forms.push({business_id:bid,revision:1,fields:[...specific.map(([fid,label,type,options])=>({id:fid,label,type,required:true,options:options||[]})),{id:'preferred_date',label:'Preferred appointment date',type:'date',required:false,options:[]},{id:'notes',label:'Anything else we should know?',type:'long_text',required:false,options:[]}]});
 }
 // Eight distinct customers per business, with consistent histories and balances.
 for(let k=0;k<8;k++){
  const u=users[(40+n+k*7)%80],past=events[k%3],rsvp=id('rsvp:'+bid+':'+u.id),mid=id('membership:'+bid+':'+u.id);
  if(u.id===owner.id||u.id===staff.id)continue;
  add('business_follows',{business_id:bid,customer_id:u.id,created_at:date(-50+k)});
  add('event_rsvps',{id:rsvp,event_id:past.id,customer_id:u.id,status:'going',party_size:k%3===0?2:1,checked_in_at:past.starts_at,checked_in_by:owner.id,created_at:date(-60)});
  add('verified_event_reviews',{id:id('review:'+rsvp),event_id:past.id,rsvp_id:rsvp,business_id:bid,customer_id:u.id,rating:k%3===0?4:5,review_text:['The team made everyone feel welcome. Clear instructions and a relaxed pace.','A lovely way to spend an afternoon locally. I learned something new and will come again.','Well organized from start to finish. The small group made it easy to ask questions.','Friendly people and thoughtful details. I have already saved their next event.'][k%4],merchant_response:k%2?'Thank you for spending time with us! We look forward to your next visit.':null,responded_by:k%2?owner.id:null,responded_at:k%2?date(-1):null,created_at:new Date(Date.parse(past.ends_at)+86400000).toISOString()});
  add('event_saves',{event_id:events[3+k%3].id,customer_id:u.id,reminder_enabled:false});
  add('event_rsvps',{id:id('future-rsvp:'+bid+':'+u.id),event_id:events[3+k%3].id,customer_id:u.id,status:'going',party_size:1,created_at:date(-1)});
  add('loyalty_memberships',{id:mid,program_id:program,business_id:bid,customer_id:u.id,is_active:true,joined_at:date(-70)});
  const visits=food?4+k:3;for(let l=0;l<visits;l++)add('loyalty_transactions',{id:id('loyalty:'+mid+':'+l),membership_id:mid,business_id:bid,transaction_type:food?'stamp':'points_earned',amount:1,actor_id:owner.id,idempotency_key:id('loyalty-key:'+mid+':'+l),note:'Playground fixture: neighborhood visit',points_amount:food?0:60+k*20,spend_minor:food?null:3000+k*1000,created_at:date(-60+l*3)});
  if(food){for(let l=0;l<3;l++){const oid=id('order:'+bid+':'+u.id+':'+l),items=rows.offering_items.filter(i=>i.business_id===bid).slice(l,l+2),sub=items.reduce((s,i)=>s+i.price_minor,0),tax=Math.round(sub*.1),status=l===2&&k===7?'refunded':'completed';add('square_orders',{id:oid,order_number:'PG-'+String(n+1).padStart(3,'0')+'-'+k+l,business_id:bid,business_name:name,customer_id:u.id,merchant_id:'fixture-no-provider',location_id:'fixture-no-provider',pickup_at:date(-3-l*7-k,17),pickup_timezone:'America/Chicago',pickup_address:b.address_line_1+', '+b.city+', LA',recipient:{name:u.name,phone:'98555501'+String(k+20)},subtotal_minor:sub,tax_minor:tax,total_minor:sub+tax,currency:'USD',status,provider:'stripe',provider_status:'COMPLETED',idempotency_key:id('order-key:'+oid),request_hash:crypto.createHash('sha256').update(oid).digest('hex'),provider_request:{fixture:true,seed},expires_at:date(-3-l*7-k,18),paid_at:date(-3-l*7-k,16),completed_at:status==='completed'?date(-3-l*7-k,18):null,refunded_at:status==='refunded'?date(-2-l*7-k):null,refunded_minor:status==='refunded'?sub+tax:0,created_at:date(-3-l*7-k,16),updated_at:date(-3-l*7-k,18)});items.forEach((it,z)=>add('square_order_items',{id:id('order-item:'+oid+':'+z),order_id:oid,snapshot:{name:it.name,quantity:'1',catalog_object_id:it.id,base_price_money:{amount:it.price_minor,currency:'USD'},total_money:{amount:it.price_minor,currency:'USD'},modifiers:[]}}));if(l===0)add('pickup_order_reviews',{id:id('order-review:'+oid),order_id:oid,business_id:bid,customer_id:u.id,rating:k%3===0?4:5,review_text:['Everything was ready when I arrived. Fresh, well packed and easy to collect.','A reliable lunch stop with friendly service. I will order again.','Great flavors and generous portions. Ordering ahead saved time.'][k%3],created_at:date(-2-k)})}}
  if(t.type==='services'){
   const service=rows.appointment_services.filter(s=>s.business_id===bid)[k%5],day=k<4?-10-k:4+k*2,start=date(day,14+(k%3)*3),end=new Date(Date.parse(start)+service.duration_minutes*60000).toISOString(),aid=id('appointment:'+bid+':'+u.id),status=k<3?'completed':k===3?'cancelled':k===4?'requested':'confirmed';
   add('appointments',{id:aid,business_id:bid,service_id:service.id,resource_id:id('resource:'+bid+':'+k%2),customer_id:u.id,customer_name:u.name,customer_phone:'98555501'+String(k+20),customer_email:u.email,customer_notes:'Playground appointment: please confirm access and preparation details in the app.',service_snapshot:{name:service.name,durationMinutes:service.duration_minutes,priceMinor:service.price_minor,currency:'USD'},policy_snapshot:{paymentPolicy:'pay_in_person',cancellationCutoffMinutes:1440},timezone:'America/Chicago',starts_at:start,ends_at:end,blocked_until:new Date(Date.parse(end)+900000).toISOString(),status,payment_status:'none',total_minor:service.price_minor,amount_due_minor:0,currency:'USD',confirmed_at:status!=='requested'?date(-15):null,completed_at:status==='completed'?end:null,idempotency_key:id('appointment-key:'+aid),request_hash:crypto.createHash('sha256').update(aid).digest('hex')});
   add('service_requests',{id:id('request:'+bid+':'+u.id),business_id:bid,customer_id:u.id,offering_item_id:service.offering_item_id,idempotency_key:id('request-key:'+bid+':'+u.id),customer_name:u.name,customer_email:u.email,request_message:`I am interested in ${service.name.toLowerCase()}. Please send an estimate and let me know what information you need before we book. ${['Weekday mornings work best for me.','I can be flexible with timing next week.','Please contact me through the app first.'][k%3]}`,preferred_timing:['Next week, weekday mornings','Friday afternoon','Within the next two weeks'][k%3],status:['new','in_review','contacted','completed','cancelled'][k%5],created_at:date(-k-1)});
  }
 }
}
for(const h of rows.business_hours) if(h.is_closed){h.opens_at=null;h.closes_at=null;}
const manifest={seed,createdAt:new Date().toISOString(),businesses,users:users.map(({password,...u})=>u),forms,rows};fs.writeFileSync(dir+'/manifest.json',JSON.stringify(manifest,null,2));
let sql='';
for(const u of users)sql+=`do $$ begin if exists(select 1 from auth.users where id=${q(u.id)} and email<>${q(u.email)}) then raise exception 'Fixture identity collision'; end if; end $$;\ninsert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,confirmation_token,recovery_token,email_change,email_change_token_new,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('00000000-0000-0000-0000-000000000000',${q(u.id)},'authenticated','authenticated',${q(u.email)},extensions.crypt(${q(u.password)},extensions.gen_salt('bf')),now(),'','','','',${q({provider:'email',providers:['email']})},${q({display_name:u.name,fixture:seed})},now(),now()) on conflict(id) do nothing;\ninsert into auth.identities(id,user_id,provider_id,identity_data,provider,created_at,updated_at) values(${q(id('identity:'+u.id))},${q(u.id)},${q(u.email)},${q({sub:u.id,email:u.email,email_verified:true})},'email',now(),now()) on conflict(provider_id,provider) do nothing;\ninsert into public.profiles(id,display_name,city,region_code,postal_code,terms_accepted_at) values(${q(u.id)},${q(u.name)},'Hammond','LA','70401',now()) on conflict(id) do nothing;\n`;
sql+='\n--SEEDBATCH--\n';
for(const [table,rs] of Object.entries(rows)){
 if(table==='businesses')sql+=`do $$ begin if exists(select 1 from public.businesses where id in (${rs.map(r=>q(r.id)).join(',')}) and slug not like 'demo-playground-%') then raise exception 'Business fixture collision'; end if; end $$;\n`;
 const cols=Object.keys(rs[0]);for(let start=0;start<rs.length;start+=150)sql+=`insert into public.${table}(${cols.join(',')}) values\n${rs.slice(start,start+150).map(r=>'('+cols.map(c=>q(r[c])).join(',')+')').join(',\n')} on conflict do nothing;\n--SEEDBATCH--\n`;
}
for(const b of businesses)sql+=`update public.businesses set location=extensions.st_setsrid(extensions.st_makepoint(${b.longitude},${b.latitude}),4326)::extensions.geography where id=${q(b.id)} and slug=${q(b.slug)};\ninsert into public.business_categories(business_id,category_id,is_primary) select ${q(b.id)},id,true from public.categories where slug=${q(b.category)} on conflict do nothing;\n`;
const suppress=`update public.notification_deliveries set status='skipped',last_error='Playground fixture: external delivery suppressed' where created_at>=transaction_timestamp() and user_id in (${users.map(u=>q(u.id)).join(',')});`;
const batches=sql.split('--SEEDBATCH--').filter(s=>s.trim()).map(s=>'begin;\n'+s+'\n'+suppress+'\ncommit;');
fs.writeFileSync(dir+'/seed.sql',batches.join('\n'));fs.writeFileSync(dir+'/forms-pending.json',JSON.stringify(forms,null,2));
console.log(JSON.stringify(Object.fromEntries(Object.entries(rows).map(([t,r])=>[t,r.length]))));
if(process.argv.includes('--apply'))(async()=>{for(let i=0;i<batches.length;i++){await query(batches[i]);if(i%10===0)console.log('Committed seed batch '+(i+1)+'/'+batches.length)}fs.writeFileSync(dir+'/seed-result.json',JSON.stringify({batches:batches.length,completed:true}));console.log('Staging playground committed. Custom forms held for the reviewed app release.');})().catch(e=>{console.error(e.message);process.exitCode=1});
module.exports={id,q,date};

