// Fictional businesses and products, deliberately varied for staging coverage.
const rows = [
 ['coffee','food_drink','coffee-tea','Coffee & tea','Coffee House','Small-batch roasts, slow mornings and a counter full of neighborhood regulars.','Coffee tasting flight',[
 ['House espresso',300,'A double shot with chocolate and toasted almond notes.'],['Vanilla oat latte',625,'Espresso with oat milk and house vanilla syrup.'],['Cane sugar cold brew',500,'Steeped overnight and served over ice.'],['Honey lavender latte',650,'Floral honey syrup with steamed whole milk.'],['Breakfast biscuit',800,'Folded egg, cheddar and pepper jelly on a warm biscuit.'],['Almond croissant',450,'Twice-baked with almond cream and sliced almonds.'],['Chai tea latte',575,'Black tea, warm spices and your choice of milk.'],['Sparkling hibiscus tea',425,'Caffeine-free hibiscus tea topped with sparkling water.']]],
 ['bakery','food_drink','bakeries','Bakeries','Bakehouse','Scratch-made bread and pastry, baked early each morning in small batches.','Sourdough shaping workshop',[
 ['Country sourdough loaf',950,'Naturally fermented for 24 hours with a crisp crust.'],['Butter croissant',425,'Flaky laminated pastry made with cultured butter.'],['Blueberry lemon muffin',375,'Fresh blueberries with a bright lemon glaze.'],['Cinnamon morning bun',475,'Brown sugar, cinnamon and cream cheese icing.'],['Chocolate pecan cookie',325,'Dark chocolate chunks and Louisiana pecans.'],['Ham and Swiss croissant',825,'Warm croissant with smoked ham and Swiss.'],['Seasonal fruit tart',650,'Vanilla pastry cream with fresh seasonal fruit.'],['Baker’s dozen rolls',1200,'Twelve soft dinner rolls plus one for the ride home.']]],
 ['brunch','food_drink','brunch','Brunch','Breakfast Kitchen','A bright all-day breakfast counter with Louisiana comfort classics and fresh seasonal plates.','Sunday brunch cooking class',[
 ['Shrimp and grits',1850,'Gulf shrimp, creamy stone-ground grits and a light pan sauce.'],['Buttermilk pancake stack',1150,'Three pancakes with whipped butter and maple syrup.'],['Boudin breakfast bowl',1400,'Crisp potatoes, boudin and two eggs.'],['Avocado sourdough toast',1050,'Smashed avocado, lemon, radish and herbs.'],['Egg and cheddar biscuit',825,'Fluffy eggs and sharp cheddar on a handmade biscuit.'],['Berry yogurt parfait',750,'Greek yogurt, berries and crunchy granola.'],['Fresh orange juice',450,'Pressed fresh and served chilled.'],['House breakfast coffee',350,'Our medium roast with free in-store refills.']]],
 ['cajun','food_drink','restaurants','Cajun & Creole','Cajun Table','Slow-simmered Louisiana recipes, generous lunch plates and family supper favorites.','Gumbo and roux demonstration',[
 ['Chicken and sausage gumbo',1250,'Dark roux gumbo with rice and green onions.'],['Crawfish étouffée',1850,'Crawfish tails in a rich sauce over steamed rice.'],['Red beans and rice',1150,'Monday-style red beans with smoked sausage.'],['Blackened catfish plate',1750,'Louisiana catfish with vegetables and seasoned rice.'],['Fried shrimp po’boy',1550,'Crisp Gulf shrimp, lettuce, tomato and remoulade.'],['Corn maque choux',550,'Sweet corn simmered with peppers and cream.'],['Bread pudding',700,'Warm custard bread pudding with praline sauce.'],['Sweet iced tea',300,'Fresh-brewed black tea over ice.']]],
 ['pizza','food_drink','restaurants','Pizza','Pizza Works','Long-fermented dough, bright tomato sauce and pizzas baked to order.','Pizza-making family night',[
 ['Margherita pizza',1400,'Tomato, fresh mozzarella, basil and olive oil.'],['Pepperoni pizza',1650,'Classic pepperoni with house tomato sauce.'],['Garden vegetable pizza',1600,'Roasted peppers, mushrooms, onion and spinach.'],['Hot honey sausage pizza',1800,'Italian sausage, chili honey and mozzarella.'],['Garlic knots',600,'Six warm knots with garlic butter and marinara.'],['Chopped Italian salad',950,'Romaine, chickpeas, olives and red wine dressing.'],['Baked ricotta dip',850,'Whipped ricotta with herbs and toasted bread.'],['Chocolate cannoli',550,'Crisp shell filled with sweet ricotta and chocolate.']]],
 ['deli','food_drink','restaurants','Sandwiches & salads','Sandwich Shop','Made-to-order sandwiches, colorful salads and quick neighborhood lunches.','Picnic pairing social',[
 ['Roast turkey club',1350,'Roasted turkey, bacon, lettuce and tomato on sourdough.'],['Pressed muffuletta',1450,'Italian meats, provolone and house olive salad.'],['Roasted vegetable sandwich',1150,'Seasonal vegetables with basil spread.'],['Chicken pesto panini',1300,'Grilled chicken, mozzarella and basil pesto.'],['Harvest grain bowl',1400,'Farro, roasted vegetables, greens and lemon dressing.'],['Crisp Caesar salad',1100,'Romaine, parmesan, croutons and Caesar dressing.'],['Tomato basil soup',600,'Slow-roasted tomato soup with basil.'],['Sea salt chips',250,'Kettle-cooked potatoes with sea salt.']]],
 ['tacos','mobile','food-trucks','Tacos & food trucks','Taco Truck','Fresh tortillas, bright salsas and quick lunches at neighborhood stops.','Taco truck community supper',[
 ['Carne asada tacos',1200,'Three corn tortillas with grilled steak, onion and cilantro.'],['Citrus chicken tacos',1100,'Three tacos with citrus-marinated chicken.'],['Roasted mushroom tacos',1050,'Three tacos with mushrooms, cabbage and avocado salsa.'],['Street corn cup',550,'Roasted corn, lime, cotija and chili.'],['Chips and guacamole',700,'Fresh guacamole with warm tortilla chips.'],['Birria quesadilla',1350,'Braised beef, melted cheese and dipping consommé.'],['Agua fresca',425,'Seasonal fruit blended with water and a little cane sugar.'],['Cinnamon churros',500,'Warm churros tossed in cinnamon sugar.']]],
 ['bbq','mobile','food-trucks','Barbecue & food trucks','Smoke Wagon','Oak-smoked meats, scratch sides and generous plates from our rolling smokehouse.','Smokehouse tasting afternoon',[
 ['Brisket plate',2100,'Sliced smoked brisket with two sides.'],['Pulled pork sandwich',1250,'Tender pork, slaw and tangy barbecue sauce.'],['Smoked chicken quarter',1450,'Dry-rubbed chicken with potato salad.'],['Sausage link basket',1100,'Smoked sausage, pickles and Texas toast.'],['Three-cheese mac',550,'Creamy baked macaroni with a golden top.'],['Mustard potato salad',450,'Red potatoes, mustard and fresh herbs.'],['Peach cobbler',650,'Warm peaches with a buttery biscuit topping.'],['Fresh lemonade',400,'Lemon juice, cane sugar and water.']]],
 ['mobilecoffee','mobile','mobile-food','Mobile coffee','Coffee Cart','Espresso and breakfast treats on the move, with a weekly route through the parish.','Coffee cart neighborhood meetup',[
 ['Iced vanilla latte',600,'Espresso, milk and vanilla over ice.'],['Hot cappuccino',475,'Double espresso topped with velvety foam.'],['Maple cold brew',550,'Smooth cold brew with maple cream.'],['Matcha oat latte',650,'Ceremonial-style matcha whisked with oat milk.'],['Chocolate milk',350,'Cold milk with dark chocolate syrup.'],['Banana bread slice',400,'Moist banana bread with toasted walnuts.'],['Savory breakfast wrap',850,'Egg, potato, cheddar and peppers.'],['Mini beignet bag',550,'Six warm beignets with powdered sugar.']]],
 ['salon','services','hair-barber','Hair & beauty','Hair Studio','Personal consultations, thoughtful cuts and color services tailored to your routine.','Styling and hair-care workshop',[
 ['Signature cut and finish',6500,'A consultation, shampoo, precision cut and styled finish.'],['Clipper cut',3500,'A detailed short cut with neckline cleanup.'],['Gloss and blowout',8500,'Refresh your tone and shine with a conditioning gloss.'],['Partial highlights',14500,'Face-framing highlights with toner and a styled finish.'],['Full color refresh',12000,'Single-process color tailored to your consultation.'],['Special occasion styling',9000,'Updo or polished waves for your event.'],['Deep conditioning treatment',2500,'A restorative conditioning treatment.'],['Fringe and neckline tidy',1800,'Quick maintenance between full appointments.']]],
 ['cleaning','services','cleaning','Cleaning services','Home Refresh','Careful home cleaning with clear estimates, consistent teams and flexible scheduling.','Healthy-home habits session',[
 ['Home cleaning consultation',0,'A 30-minute walkthrough to build an accurate cleaning plan.'],['Standard home clean',15000,'Kitchen, bathrooms, living areas and bedrooms; up to 1,500 square feet.'],['Deep clean',26000,'Detailed first-visit clean including baseboards and appliance exteriors.'],['Move-out clean',32000,'An empty-home clean for a fresh handover.'],['Kitchen detail',8500,'Cabinet fronts, backsplash, counters and appliance exteriors.'],['Bathroom refresh',6500,'Fixtures, tile, mirrors and floors in one bathroom.'],['Window interior clean',9500,'Interior glass and accessible window tracks.'],['Recurring clean planning',0,'Choose a weekly, biweekly or monthly schedule.']]],
 ['hvac','services','home-services','Heating & air','Comfort Services','Seasonal maintenance, diagnostic visits and transparent home comfort estimates.','Home comfort and filter clinic',[
 ['Cooling diagnostic visit',9500,'Evaluate cooling performance and discuss repair options.'],['Seasonal tune-up',12500,'A preventive check of your heating and cooling system.'],['New system estimate',0,'On-site measurement and a written replacement estimate.'],['Thermostat installation',14500,'Install a customer-supplied compatible thermostat.'],['Indoor air consultation',7500,'Review filtration, airflow and indoor air concerns.'],['Heating safety check',11000,'Inspect heating operation before colder weather.'],['Duct inspection',8500,'Inspect accessible ducts and discuss improvements.'],['Maintenance plan consultation',0,'Plan annual care for your equipment.']]],
 ['landscape','services','landscaping-lawn-care','Lawn & garden','Garden Care','Reliable lawn care and planting advice suited to Louisiana gardens.','Native garden planting workshop',[
 ['Garden consultation',6500,'Walk through your landscape and develop a seasonal plan.'],['Lawn mow and edge',6000,'Mowing, edging and cleanup for a standard residential yard.'],['Seasonal bed refresh',18000,'Weeding, edging and fresh mulch for existing beds.'],['Native planting plan',14500,'A tailored list and layout for native plants.'],['Shrub shaping',9500,'Shape and maintain established shrubs.'],['Irrigation check',8500,'Check accessible heads, timers and watering coverage.'],['Leaf cleanup',11000,'Collect leaves from lawns and landscaped areas.'],['Landscape estimate',0,'A project visit and itemized landscape estimate.']]],
 ['pet','services','pet-care','Pet grooming','Pet Parlour','Low-stress grooming appointments with time to understand your pet’s needs.','Puppy care introduction',[
 ['Small dog full groom',6500,'Bath, dry, brush, haircut and nails for dogs under 25 pounds.'],['Medium dog full groom',8000,'Full grooming for dogs from 25 to 50 pounds.'],['Large dog full groom',10000,'Full grooming for dogs over 50 pounds.'],['Bath and brush',4500,'Gentle bath, dry and thorough brushing.'],['Nail trim',1800,'A careful nail trim and smoothing.'],['Puppy introduction',3500,'A short positive first grooming experience.'],['Deshedding treatment',2500,'Coat care to reduce loose undercoat.'],['Sensitive skin bath',5000,'A gentle bath using fragrance-free products.']]],
 ['boutique','retail','boutiques','Boutiques','Boutique','Thoughtfully chosen clothing and accessories for everyday life and special plans.','Fall capsule styling evening',[
 ['Linen weekend blouse',5800,'Relaxed linen blend with shell buttons.'],['Everyday crossbody bag',4200,'Compact bag with an adjustable woven strap.'],['Gold hoop earrings',2200,'Lightweight gold-tone everyday hoops.'],['Soft knit cardigan',6400,'An easy layer with patch pockets.'],['Printed midi dress',8200,'A flowing midi dress with side pockets.'],['Silk-feel neck scarf',1800,'A versatile printed scarf.'],['Woven weekend tote',4600,'Roomy woven tote with sturdy handles.'],['Personal styling appointment',0,'A friendly 30-minute styling session.']]],
 ['gifts','retail','gift-shops','Gift shops','Gift Shop','Locally inspired gifts, useful little luxuries and thoughtful wrapping.','Meet the makers market',[
 ['Louisiana welcome box',4500,'A selection of regionally inspired treats and keepsakes.'],['Magnolia soy candle',2400,'Hand-poured candle in a reusable glass jar.'],['Local artist card set',1800,'Six illustrated blank greeting cards.'],['Handmade ceramic mug',2800,'A glazed stoneware mug with a comfortable handle.'],['Parish tea towel',1600,'Cotton towel with an illustrated local map.'],['Self-care gift basket',6500,'Bath soak, candle, tea and a handwritten note.'],['Pocket field journal',1400,'A small notebook for daily notes and sketches.'],['Gift wrapping service',600,'Paper, ribbon and a handwritten gift tag.']]],
 ['florist','retail','florists','Florists','Flower Studio','Seasonal stems, expressive arrangements and thoughtful flowers for life’s occasions.','Seasonal flower arranging',[
 ['Seasonal wrapped bouquet',3500,'A hand-tied mix of fresh seasonal stems.'],['Garden vase arrangement',6500,'A lush arrangement in a reusable glass vase.'],['Petite desk flowers',2800,'A compact arrangement for a desk or bedside.'],['Celebration bouquet',8500,'An abundant hand-tied bouquet for a special day.'],['Dried flower wreath',5500,'Natural dried flowers on a woven base.'],['Orchid plant',5800,'An orchid in a simple ceramic planter.'],['Event floral consultation',0,'Discuss colors, venue and arrangements for your gathering.'],['Flower care kit',1200,'Shears, food packets and a care guide.']]],
 ['clothing','retail','clothing','Clothing shops','Clothing Co.','Comfortable essentials, durable layers and an approachable fit-focused team.','Denim and fit clinic',[
 ['Cotton everyday tee',2600,'Soft cotton crewneck in seasonal colors.'],['Relaxed chino trousers',6800,'Easy-fitting chinos with a little stretch.'],['Canvas weekend jacket',8900,'Lightweight canvas with roomy pockets.'],['Parish embroidered cap',2400,'Adjustable cotton cap with local embroidery.'],['Straight-leg denim',7800,'Mid-rise denim designed for everyday wear.'],['Ribbed tank top',2200,'Cotton rib knit with a clean neckline.'],['Merino blend socks',1600,'Soft crew socks with reinforced heels.'],['Fit consultation',0,'Find cuts and sizes that work for your routine.']]],
 ['music','entertainment_venue','live-music','Live music','Listening Room','A welcoming room for local musicians, acoustic sets and community evenings.','Northshore acoustic showcase',[
 ['Acoustic show admission',1800,'General admission to an intimate live performance.'],['Reserved table for two',4500,'Two seats at a reserved table near the stage.'],['Songwriter circle admission',1200,'An evening of original songs and stories.'],['Open mic registration',0,'Reserve a performance slot for open mic night.'],['Private room consultation',0,'Tour the venue and discuss a private event.'],['Community jazz admission',2000,'An evening with local jazz musicians.'],['Venue poster print',2500,'A limited-run illustrated concert poster.'],['House sparkling lemonade',500,'Fresh lemon and sparkling water.']]],
 ['arts','entertainment_venue','arts-entertainment','Arts & workshops','Maker Studio','Hands-on creative workshops, open studio time and friendly instructors.','Clay and color workshop',[
 ['Beginner pottery workshop',6500,'Two hours of hand-building with clay and an instructor.'],['Watercolor afternoon',4500,'Explore color mixing and a simple landscape.'],['Printmaking introduction',5500,'Carve a small block and print your own design.'],['Open studio pass',2500,'Three hours of studio access for independent projects.'],['Family clay session',7500,'A shared clay project for one adult and child.'],['Private workshop consultation',0,'Plan a creative gathering for your group.'],['Ceramic project kit',3200,'Materials and instructions for a home project.'],['Gallery artist print',3500,'An archival print from a featured local artist.']]],
];
module.exports=rows.map(([key,type,category,label,suffix,description,event,items])=>({key,type,category,label,suffix,description,event,items}));
