import {describe,it,expect,vi} from 'vitest';
import {createMobileModerationClient} from './mobile-moderation-client';
import {caseBrief} from './case-brief';
import type {BackupSettings} from './backup-types';
import type {ModerationRecord} from './moderation-types';
const account='a0000000-0000-4000-8000-000000000001',id='c0000000-0000-4000-8000-000000000001';
const status={policy:{mode:'dry_run',missing_information:true,promotional_reviews:true,internal_flags:true,version:'backup-1.0.0',revision:'a'.repeat(32),updated_at:'2026-10-07T00:00:00Z'},runs:[],handled:0};
const preview={request_id:id,mode:'dry_run',version:'backup-1.0.0',dry_run:true,scanned:0,applied:0,flagged:0,manual_overrides:0,entries:[]};
const input:BackupSettings=Object.freeze({mode:'enabled',missing:true,spam:true,flags:true,reason:'Synthetic local configuration check.',revision:'a'.repeat(32),requestId:id});
function fixture(){let scope:string|null=account;const rpc=vi.fn(async(name:string,_args?:Record<string,unknown>):Promise<{data:unknown;error:{code:string}|null}>=>({data:name==='is_platform_admin'?true:name==='run_moderation_backup'?preview:status,error:null}));
 const client=createMobileModerationClient({auth:{getUser:async()=>({data:{user:scope?{id:scope}:null},error:null})},rpc},()=>scope);
 return {client,rpc,change:(next:string|null)=>scope=next};}
describe('native moderation backup boundaries',()=>{
 it('does not call backup while signed out',async()=>{const f=fixture();f.change(null);await expect(f.client.backupStatus(null)).rejects.toMatchObject({kind:'signed_out'});expect(f.rpc).not.toHaveBeenCalled();});
 it('rechecks role before each protected read and setting mutation',async()=>{const f=fixture();await f.client.backupStatus(account);await f.client.configureBackup(account,input);expect(f.rpc.mock.calls.map(x=>x[0])).toEqual(['is_platform_admin','get_moderation_backup_status','is_platform_admin','configure_moderation_backup']);});
 it('a preview sends p_apply false and the supplied stable request ID',async()=>{const f=fixture();await f.client.previewBackup(account,id);expect(f.rpc).toHaveBeenLastCalledWith('run_moderation_backup',{p_apply:false,p_request_id:id,p_limit:50});});
 it('revoked admin cannot run or configure backup',async()=>{const f=fixture();f.rpc.mockResolvedValue({data:false,error:null});await expect(f.client.previewBackup(account,id)).rejects.toMatchObject({kind:'denied'});expect(f.rpc.mock.calls).toHaveLength(1);});
 it('drops a protected response after account switching',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>{if(name==='is_platform_admin')return {data:true,error:null};f.change('a0000000-0000-4000-8000-000000000002');return {data:status,error:null};});await expect(f.client.backupStatus(account)).rejects.toMatchObject({kind:'session_changed'});});
 it('rejects malformed policy and preview responses',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>({data:name==='is_platform_admin'?true:{},error:null}));await expect(f.client.backupStatus(account)).rejects.toMatchObject({kind:'unavailable'});await expect(f.client.previewBackup(account,id)).rejects.toMatchObject({kind:'unavailable'});});
 it('rejects null recent runs instead of returning a value that crashes the activity panel',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>({data:name==='is_platform_admin'?true:{...status,runs:[null]},error:null}));await expect(f.client.backupStatus(account)).rejects.toMatchObject({kind:'unavailable'});});
 it('rejects a malformed proposed entry before the panel reads its fields',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>({data:name==='is_platform_admin'?true:{dry_run:true,entries:[null]},error:null}));await expect(f.client.previewBackup(account,id)).rejects.toMatchObject({kind:'unavailable'});});
 it('treats malformed saved activity as an uncertain settings result for exact retry',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>({data:name==='is_platform_admin'?true:{...status,runs:[{request_id:id,entries:null}]},error:null}));await expect(f.client.configureBackup(account,input)).rejects.toMatchObject({kind:'uncertain'});});
 it('accepts complete server runs and all three legitimate proposed action shapes',async()=>{const f=fixture();const run={...preview,entries:[{kind:'business',id,rule:'missing_publication_fields',action:'request_info',reason:'Missing publication hours.',evidence:{missing_keys:['hours']},applied:false},{kind:'pickup_review',id,rule:'review_promotion_template',action:'hide',reason:'Repeated template.',evidence:{links:3,repeated_promotions:2},applied:false},{kind:'content_report',id,rule:'context_needs_review',action:'flag',reason:'Check shared context.',evidence:{matches_or_other_reports:1,nearby_activity:3},applied:false}]};f.rpc.mockImplementation(async name=>({data:name==='is_platform_admin'?true:name==='run_moderation_backup'?run:{...status,runs:[run]},error:null}));expect(await f.client.previewBackup(account,id)).toEqual(run);expect((await f.client.backupStatus(account)).runs).toEqual([run]);});
 it('keeps uncertain settings retry arguments and does not silently enable again',async()=>{const f=fixture();f.rpc.mockImplementation(async name=>{if(name==='is_platform_admin')return {data:true,error:null};throw Error('Connection interrupted');});await expect(f.client.configureBackup(account,input)).rejects.toMatchObject({kind:'uncertain'});await expect(f.client.configureBackup(account,input)).rejects.toMatchObject({kind:'uncertain'});const requests=f.rpc.mock.calls.filter(x=>x[0]==='configure_moderation_backup');expect(requests[0]?.[1]).toEqual(requests[1]?.[1]);expect(input.requestId).toBe(id);});
 it('plain case summary explains an allegation, low rating and a reversible backup outcome',()=>{
  const r:ModerationRecord={kind:'pickup_review',id,title:'Synthetic bakery',subtitle:'Verified pickup review',status:'resolved',content_status:'hidden',created_at:'2026-10-07T00:00:00Z',text:'Synthetic one-star review.',reason:'inaccurate',details:'Synthetic allegation.',resolution_note:null,revision:'a'.repeat(32),readiness:null,duplicates:2,activity_count:1,context:{rating:1},history:[{id:1,action:'moderation_hide',actor:'Administrator',created_at:'2026-10-07T00:00:00Z',details:{automation:{version:'backup-1.0.0',rule:'review_promotion_template',evidence:{links:3}}}}]};
  const brief=caseBrief(r);expect(brief.happened).toContain('claim to check');expect(brief.evidence.join(' ')).toContain('low rating is not a reason');expect(brief.backup).toContain('backup');expect(brief.undo.length).toBeGreaterThan(10);
 });
});
