/** Exact Lucide 1.52.0 subset of the shared Parish Pass icon family.
 * Generated by task5/build-admin-icon-subset.cjs for the bounded admin integration.
 * ISC copyright Lucide Contributors; see LICENSE.lucide. No platform symbol substitution. */
export const adminIconNodes = {
  store: [
    [
      'path',
      {
        d: 'M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5',
      },
    ],
    [
      'path',
      {
        d: 'M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244',
      },
    ],
    [
      'path',
      {
        d: 'M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05',
      },
    ],
  ],
  flag: [
    [
      'path',
      {
        d: 'M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528',
      },
    ],
  ],
  'shopping-bag': [
    [
      'path',
      {
        d: 'M16 10a4 4 0 0 1-8 0',
      },
    ],
    [
      'path',
      {
        d: 'M3.103 6.034h17.794',
      },
    ],
    [
      'path',
      {
        d: 'M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z',
      },
    ],
  ],
  'calendar-days': [
    [
      'path',
      {
        d: 'M8 2v3',
      },
    ],
    [
      'path',
      {
        d: 'M16 2v3',
      },
    ],
    [
      'rect',
      {
        x: '3',
        y: '3',
        width: '18',
        height: '18',
        rx: '2',
      },
    ],
    [
      'path',
      {
        d: 'M3 9h18',
      },
    ],
    [
      'path',
      {
        d: 'M8 13h.01',
      },
    ],
    [
      'path',
      {
        d: 'M12 13h.01',
      },
    ],
    [
      'path',
      {
        d: 'M16 13h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8 17h.01',
      },
    ],
    [
      'path',
      {
        d: 'M12 17h.01',
      },
    ],
    [
      'path',
      {
        d: 'M16 17h.01',
      },
    ],
  ],
  'circle-check': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'm16 9-5.5 5.5L8 12',
      },
    ],
  ],
  'layout-grid': [
    [
      'rect',
      {
        width: '7',
        height: '7',
        x: '3',
        y: '3',
        rx: '1',
      },
    ],
    [
      'rect',
      {
        width: '7',
        height: '7',
        x: '14',
        y: '3',
        rx: '1',
      },
    ],
    [
      'rect',
      {
        width: '7',
        height: '7',
        x: '14',
        y: '14',
        rx: '1',
      },
    ],
    [
      'rect',
      {
        width: '7',
        height: '7',
        x: '3',
        y: '14',
        rx: '1',
      },
    ],
  ],
  clock: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M12 6v6l4 2',
      },
    ],
  ],
  'arrow-right': [
    [
      'path',
      {
        d: 'M5 12h14',
      },
    ],
    [
      'path',
      {
        d: 'm12 5 7 7-7 7',
      },
    ],
  ],
  'circle-help': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3',
      },
    ],
    [
      'path',
      {
        d: 'M12 17h.01',
      },
    ],
  ],
  'circle-alert': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'line',
      {
        x1: '12',
        x2: '12',
        y1: '8',
        y2: '12',
      },
    ],
    [
      'line',
      {
        x1: '12',
        x2: '12.01',
        y1: '16',
        y2: '16',
      },
    ],
  ],
  'file-text': [
    [
      'path',
      {
        d: 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      },
    ],
    [
      'path',
      {
        d: 'M14 2v5a1 1 0 0 0 1 1h5',
      },
    ],
    [
      'path',
      {
        d: 'M10 9H8',
      },
    ],
    [
      'path',
      {
        d: 'M16 13H8',
      },
    ],
    [
      'path',
      {
        d: 'M16 17H8',
      },
    ],
  ],
  circle: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
  ],
  bell: [
    [
      'path',
      {
        d: 'M10.268 21a2 2 0 0 0 3.464 0',
      },
    ],
    [
      'path',
      {
        d: 'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
      },
    ],
  ],
  'chevron-left': [
    [
      'path',
      {
        d: 'm15 18-6-6 6-6',
      },
    ],
  ],
} as const;
