import { StyleSheet } from 'react-native';
/** Presentation handoff: task5 may refine these styles without changing transport or state guards. */
export const adminStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F4F2E9' },
  content: { padding: 20, paddingBottom: 40, gap: 20 },
  top: { gap: 12 },
  header: { fontSize: 28, lineHeight: 34, fontWeight: '700', color: '#102D25' },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: '#DBE2DB',
  },
  title: { fontSize: 19, lineHeight: 25, fontWeight: '700', color: '#102D25' },
  body: { fontSize: 16, lineHeight: 24, color: '#102D25' },
  muted: { fontSize: 14, lineHeight: 21, color: '#456052' },
  notice: { padding: 16, borderRadius: 12, backgroundColor: '#E3F1E7', gap: 8 },
  error: { padding: 16, borderRadius: 12, backgroundColor: '#FFF0ED', gap: 8 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, alignItems: 'center' },
  choice: {
    minHeight: 48,
    padding: 14,
    borderWidth: 1,
    borderColor: '#C8D5CA',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
  },
  selected: { backgroundColor: '#89C9A2', borderColor: '#176B4D' },
  disabled: { opacity: 0.5 },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#AEC3B6',
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    lineHeight: 24,
    color: '#102D25',
    backgroundColor: '#FFFFFF',
  },
  multiline: { minHeight: 110, textAlignVertical: 'top' },
  item: { gap: 7 },
  separator: { borderTopWidth: 1, borderTopColor: '#DBE2DB', paddingTop: 12 },
});
